### ISSUE TITLE
cannot find patch_rt file after patch 1.23.0

### ISSUE THREAD

**Issue by thcchoi** [jncraton/BWMetaAI#20]
I have truly been enjoying your AI patch so far.

However after 1.23.0 patch there is no longer patch_rt file.

Is it possible for you to address this issue?

Any help or advice will be much appreciated :)

**Comment by BoneHorror** [comment]
Seeing as Blizz removed all mpq archives from RM, I think Craton will have to switch to Samase. Which is a great opportunity to start using AISE, but it will take some work :P

**Comment by thcchoi** [comment]
Looking forward to the new update frm u :)

**Comment by jncraton** [comment]
Thanks for bringing this to my attention. I unfortunately don't have much time to commit to this project currently, and it sounds like this will be a fairly significant adjustment, as I'll need to learn some new tools. All that should need to happen is for the `aiscript.bin` from this project to be injected into the game somehow. I'm not familiar with the current tools to do this, nor do I know if they will work right away with the new patch.

Long term, I'd love to get UMS builds that work properly and don't require any modding. I tried this briefly (https://github.com/jncraton/BWMetaAI/releases/download/v2.1/2.Destination.BWMetaAI.Protoss.scx), but there seem to be issues with the scripts when they are used in UMS maps rather than melee.

I'm certainly open to suggestions and/or PRs to get this working again.

**Comment by thcchoi** [comment]
looks like patch_rt file is back
hopefully it never disappears again ;)

**Comment by thcchoi** [comment]
looks like the patch_rt file is back but this AI patch no longer works when it replaced the original file....

**Comment by BoneHorror** [comment]
I will make a working samase build with it later tonight and see if the freeze issue still occurs.

**Comment by jncraton** [comment]
I've created some new EUD maps to try out. I haven't tested them extensively, but the Protoss AI worked for me in my limited testing.

You should be able to play against the AI by simply starting a single player UMS game on one of the maps found here:

https://github.com/jncraton/BWMetaAI/releases/tag/v2.3-alpha

**Comment by BoneHorror** [comment]
Forgot to follow up on my previous comment - the freeze issue no longer occured (at least in a limited number of test runs), but the AI just feels borked instead. Way slower than normal BWMeta D:

**Comment by jncraton** [comment]
@BoneHorror Thanks for the update. I'm glad it's at least working a little bit.

**Comment by pha3z** [comment]
Just chiming in.  I have been lurking and watching this issue for the last month or so.  I never got to even try BWMeta before the recent BW Update that has caused this compatibility issue.  I am really hoping to get a chance to try out BW Meta.  My family plays cooperatively on LAN against AI a lot, and we're pretty tired of the stock brood war AI doing the same dumb strategies over and over.

I'm very greatful BoneHorror is working on this. :) Do we anticipate regaining compatibility with the current version of BW?

I wish I could help, but I work in other languages, and I really wouldn't be of much use for this project.

**Comment by BoneHorror** [comment]
It's highly unlikely I will manage to make it work without issues using samase, so your best bet for playing vs BWMetaAI using JNCraton's EUD maps. I'm kind of too busy working on my Starcraft campaign to force either of our programmers to look into the PyAI compile bugs D:

**Comment by pha3z** [comment]
Bummer. Appreciate your time though! Thank you. :)

**Comment by tastynibling** [comment]
Samase works great for me. Didn't notice any problems. The timings in my custom builds still work. I encourage everyone to give this a try.

1. Get [Samase](http://www.staredit.net/topic/17430/0/)
2. Get aiscript.bin from BWMetaAI's releases page
3. Make the directory layout like this:
StarCraft\x86\StarCraft.exe
StarCraft\x86\sesame.exe
StarCraft\x86\\*custom*\scripts\aiscript.bin
4. Make a shortcut to sasame.exe and add *custom* as a command line parameter.

The name *custom* can be anything you want. Just make sure the directory and parameter match.

**Comment by jncraton** [comment]
Great! I'm glad that you were able to get this working. Thanks for sharing the details for others!

**Comment by thcchoi** [comment]
this works like a charm!!! thx heaps! now we can enjoy playing BWMetaAI again!
Looking forward to more updates too!!

**Comment by jncraton** [comment]
Samase appears to be a workable method going forward, so I've updated the readme (1d29b9a87647eca0b213a102f9eff37cbd6deb16) to include using Samase for launching. Thanks @tastynibling for the instructions.

Please let me know if these instructions can be improved. I'm not very familiar with Samase, and I very rarely use Windows these days.

**Comment by cla111** [comment]
Hi I am playing the normal starcraft broodwar through battle.net may I know how do make the A.I more harder and effective in the multiplayer game ? thank you

**Comment by TreesAreTough** [comment]
Samase has never worked for me. These have  gone over and retried the instructions quite a few times at this point.
    
"Get Samase
    Get aiscript.bin from BWMetaAI's releases page
    Make the directory layout like this:
    StarCraft\x86\StarCraft.exe
    StarCraft\x86\sesame.exe
    StarCraft\x86\custom\scripts\aiscript.bin
    Make a shortcut to sasame.exe and add custom as a command line parameter.
The name custom can be anything you want. Just make sure the directory and parameter match."

I have tried many times and this does not work for me. Can someone explain more of why you need to do a shortcut with a command line parameter. I have also tried the method of packing them together to make an exe and that will launch the game but its just the normal AI. Any tips?

**Comment by BoneHorror** [comment]
Create a bat file with a command similar to this except with names changed to whatever you have
:retry
samase.exe C:\samase\uedaip --pack C:\samase\uedaip.exe || pause
if errorlevel 1 goto retry
where \uedaip is a folder in which you have a scripts folder that has the bwmetaai scritps inside of them. If you're familiar with how command line programs work, samase is exactly the same. If it's not working, you're doing something wrong. Try googling until you can figure out how to launch programs from the command line.

**Comment by BoneHorror** [comment]
screw it, I wanted to write it like above since just making an exe makes it an outdated solution if there's another major patch, but here's an exe for the current samase/scr patch https://mega.nz/file/9toGwYKR#rYMSCMWBdncB5zNRbbv3DLVbl1tKWVRvwQUMUMZSxvs

**Comment by TreesAreTough** [comment]
> 
> 
> screw it, I wanted to write it like above since just making an exe makes it an outdated solution if there's another major patch, but here's an exe for the current samase/scr patch https://mega.nz/file/9toGwYKR#rYMSCMWBdncB5zNRbbv3DLVbl1tKWVRvwQUMUMZSxvs

Thank you for your quick reply and current patch solution. I learned a little bit and got it working just now. I can see now I was up way too late trying and I got in a frustration cloud. I appreciate the info and help.
