### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by victorsena13** [jncraton/BWMetaAI#22]
i've tried this samase method it ran but i doesn't seem to work, idk if i'm doing something wrong or it's not working anymore. What i do:

run samase from power shell  like this: 
 .\samase.exe D:\Victor\Battle.net\Games\StarCraft\x86\custom\scripts

the aiscript is inside this folder.

**Comment by jncraton** [comment]
I haven't had a chance to hop on a Windows machine and test this out, but that path name is different than the one used over here:

https://github.com/jncraton/BWMetaAI/issues/21

You used:

`StarCraft\x86\custom\scripts`

They used:

`StarCraft\x86_custom_\scripts\aiscript.bin`

They also recommended using simply `custom` as the parameter rather than a full path to the script. I'd try varying the script location and parameter to see if that helps.

**Comment by victorsena13** [comment]
> I haven't had a chance to hop on a Windows machine and test this out, but that path name is different than the one used over here:
> 
> #21
> 
> You used:
> 
> `StarCraft\x86\custom\scripts`
> 
> They used:
> 
> `StarCraft\x86_custom_\scripts`
> 
> They also recommended using simply `custom` as the parameter rather than a full path to the script. I'd try varying the script location and parameter to see if that helps.

Hi, with the help of the forum on Samase i managed to make it run, thanks :)

**Comment by jncraton** [comment]
Great! Any chance you could link to the forum post and/or explain what worked in case others run into this problem?

**Comment by victorsena13** [comment]
sure as soon as i get home i post here, any chance for more updates? New builds or more Agressive AI. Or any place that i can learn to make a custom AI like this one?

**Comment by jncraton** [comment]
Sounds good. There's always opportunity for updates. If you have ideas for new builds, please let me know.

There's various info around the net about this type of modding. I've included the best community documentation for the AI script command I could find here:

https://github.com/jncraton/BWMetaAI/blob/master/docs/command_info.md

PyMS and particularly PyAI is probably a good place to start:

https://github.com/poiuyqwert/PyMS

**Comment by victorsena13** [comment]
First you need the aiscript.bin file from BWMetaAI. I don't know if there's a direct download for it, if its download links only provide you with a .mpq file then you can open that MPQ with a program like WinMPQ or Ladik's MPQ Editor and extract aiscript.bin.

Create a new folder, let's say for example C:\mod and another folder inside it named 'scripts' and place aiscript.bin there (So C:\mod\scripts\aiscript.bin)

Open command line, run
Code
C:\path\to\samase.exe C:\mod --pack C:\mod\BWMetaAI.exe

(Obviously use whatever path you had samase downloaded to)

Now you should have BWMetaAI.exe in C:\mod which should launch the mod.

---

If your antivirus has an issue with newly created exes you can also just launch BW directly with
Code
C:\path\to\samase.exe C:\mod

but then you probably want to save the command in a .bat file/shortcut with arguments instead of typing that every time.
