### ISSUE TITLE
Does it work for Starcraft: Remastered + MacOS?

### ISSUE THREAD

**Issue by pangrr** [jncraton/BWMetaAI#23]
So happy to find this package!

I installed Starcraft: Remastered from Battle.net in MacOS. Does this package work? Or I have to install in windows?

**Comment by jncraton** [comment]
It should work, in theory, if there were a way to load the aiscript.bin file into the running game on Mac. This is done using Samase on Windows, but Samase is unfortunately not supported on Mac. The modding community tends to be Windows dominated.

You should be able to use 1.16 on Mac, but I haven't personally tested that, and you'd lose all of the benefits of Remasted. 1.16 does work well on Linux. Windows is probably your best bet for using Remastered.

**Comment by pangrr** [comment]
I will try windows 10 + remastered.
By the way, do you know the easiest way to use advanced AI in remastered? What I found online is pretty complicated to use and is for 1.16.

**Comment by jncraton** [comment]
Sounds good. Good luck!

What sort of "advanced" AI are you referring to?

**Comment by pangrr** [comment]
Thank you!

Something like [this](https://tl.net/forum/brood-war/531310-human-like-broodwar-ais-revamped?view=all) or what you mentioned in README that use BWAPI. I just want to play with smarter computer.

**Comment by jncraton** [comment]
I see. I've not run anything BWAPI-based with Remastered, so I can't really help you there.

**Comment by pangrr** [comment]
Thank you very much anyway:)
