### ISSUE TITLE
error running script *too new* version 1.23.3

### ISSUE THREAD

**Issue by terry-jr** [jncraton/BWMetaAI#25]
I spent some time tonight getting samase to pack the ai script. which i did so with success but when i try and run the .exe and select the starcraft executable i get an error saying this:
![starcraft error](https://user-images.githubusercontent.com/64460951/80458000-03bfa100-88e5-11ea-851e-30ddb63c1711.JPG)

I tried to run the script in 1.16 and it said that i needed 1.20 or newer. I am on 1.23.3.8211 which was updated 2/12/2020. my buddy is saying there might be a way for you to just update the version in the script? please let me know. 

--side note--
if this issue is fixed i will make a legit tutorial on how to pack up the script as it was pretty tricky for a n00b like me. i very briefly got to use this tool last year before they got rid of "patch_rt" support and think its a great tool that deserves to be used by newer players. thanks for making this, i hope its an easy fix!

**Comment by BoneHorror** [comment]
Update samase, there was a patch that broke it semi-recently. I'm working with samase and it's newest update works fine on current bnet version

**Comment by jncraton** [comment]
@terry-jr Were you able to get this working with the newest version of Samase?
