### ISSUE TITLE
starcraft broodwar patch 1.23.0

### ISSUE THREAD

**Issue by cla111** [jncraton/BWMetaAI#26]
Hi I am playing the normal starcraft broodwar through battle.net may I know how do make the A.I more harder and effective in the multiplayer game ? thank you

**Comment by jncraton** [comment]
As far as I know, the [Samase patching method](https://github.com/jncraton/BWMetaAI#starcraft-remastered-samase-method-version-118) should work on Battle.net, as long as both players are patched to the same version of the AI script.

Note that Samase generally has to be modified to work with new SC:R patches, so you'll need the latest version, and it may not work right away after a patch drops.

Multiplayer on 1.16 should be reliable using the [patch_rt.mpq method](https://github.com/jncraton/BWMetaAI#version-1161-and-lower) as long as both players are using the same version or patch_rt.mpq.
