### ISSUE TITLE
Hi i can not open the samase.exe

### ISSUE THREAD

**Issue by Ringo742** [jncraton/BWMetaAI#28]
Hi i can not open the samase.exe even if  i add custom as command-line-parameter. Do any other people have the same problem ? i don not have python on my computers, do i have to install it ?

**Comment by BoneHorror** [comment]
You don't need to open the exe at all, you just use it through a .bat script. Samase has no gui to use

**Comment by Ringo742** [comment]
> You don't need to open the exe at all, you just use it through a .bat script. Samase has no gui to use

so i can run the starcraft.exe directly ? Could you tell me how to do then ? i am not skilled at computer operation.

**Comment by Ringo742** [comment]
i try to open samase.exe-shortcut with starcraft.exe. But when i find it is the origin ai

**Comment by MBguity** [comment]
Hey Im going to copy paste my reply to the other guy who get sesame.exe to work.

Basically go to your StarCraft folder (It's usually in Program Files on your main drive). Then open up the x86 folder. Inside you will find Starcraft.exe. Now put the original "sesame.exe" in the same folder as Starcraft.exe (I will call this folder x86 from now on). Make a shortcut for sesame.exe and place it on your desktop.

Next in the x86 folder, open custom (if you dont have this folder already, make a new one and name it custom), now inside custom, open scripts (if you dont have this folder already, make a new one and name it scripts). Drag and drop your downloaded aiscript.bin file into the newly created scripts folder.

Now last step. On your desktop, you created a shortcut for sesame.exe. Right click the shortcut, click on properties. Under the "Shortcut" tab, find the "Target" field. Inside the target field add after everything " custom" (That's a space, then the word custom) It should look SOMETHING like "C:\Program Files (x86)\StarCraft\x86\samase-0.7.0.exe" custom

Now make sure your Broodwar is updated, and double click your sesame.exe shortcut to open the game.

Now it works, even over battlenet!

**Comment by Ringo742** [comment]
thanks a lot, I get it work now



------------------&nbsp;Original message&nbsp;------------------
From: "MBguity"; 
Sendtime: Saturday, Jun 12, 2021 4:34 AM
To: "jncraton/BWMetaAI"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [jncraton/BWMetaAI] Hi i can not open the samase.exe (#28)





 
Hey Im going to copy paste my reply to the other guy who get sesame.exe to work.
 
Basically go to your StarCraft folder (It's usually in Program Files on your main drive). Then open up the x86 folder. Inside you will find Starcraft.exe. Now put the original "sesame.exe" in the same folder as Starcraft.exe (I will call this folder x86 from now on). Make a shortcut for sesame.exe and place it on your desktop.
 
Next in the x86 folder, open custom (if you dont have this folder already, make a new one and name it custom), now inside custom, open scripts (if you dont have this folder already, make a new one and name it scripts). Drag and drop your downloaded aiscript.bin file into the newly created scripts folder.
 
Now last step. On your desktop, you created a shortcut for sesame.exe. Right click the shortcut, click on properties. Under the "Shortcut" tab, find the "Target" field. Inside the target field add after everything " custom" (That's a space, then the word custom) It should look SOMETHING like "C:\Program Files (x86)\StarCraft\x86\samase-0.7.0.exe" custom
 
Now make sure your Broodwar is updated, and double click your sesame.exe shortcut to open the game.
 
Now it works, even over battlenet!
