### ISSUE TITLE
Hi. How to install game [newbie here]

### ISSUE THREAD

**Issue by kvnllnd** [jncraton/BWMetaAI#29]
Hi. I am not a programmer. But a rather avid broodwar geek.

I find this project fascinating. I have game version 1.23.8

So I am trying to follow the Samase instruction but couldn't get the part about this:

Make the directory layout like this:
StarCraft\x86\StarCraft.exe
StarCraft\x86\sesame.exe
StarCraft\x86\custom\scripts\aiscript.bin
Make a shortcut to sasame.exe and add custom as a command line parameter.

Can someone explain it in more detail. Thanks a lot.

**Comment by MBguity** [comment]
Hey Im surprised no one has gotten back to you about this yet.

Basically go to your StarCraft folder (It's usually in Program Files on your main drive). Then open up the x86 folder. Inside you will find Starcraft.exe. Now put the original "sesame.exe" in the same folder as Starcraft.exe (I will call this folder x86 from now on). Make a shortcut for sesame.exe and place it on your desktop. 

Next in the x86 folder, open custom (if you dont have this folder already, make a new one and name it custom), now inside custom, open scripts  (if you dont have this folder already, make a new one and name it scripts). Drag and drop your downloaded aiscript.bin file into the newly created scripts folder. 

Now last step. On your desktop, you created a shortcut for sesame.exe. Right click the shortcut, click on properties. Under the "Shortcut" tab, find the "Target" field. Inside the target field add after everything " custom" (That's a space, then the word custom) It should look SOMETHING like "C:\Program Files (x86)\StarCraft\x86\samase-0.7.0.exe" custom

Now make sure your Broodwar is updated, and double click your sesame.exe shortcut to open the game.

Now it works, even over battlenet!

Sorry that this reply was sooooo late!
