### ISSUE TITLE
Zerg is too passive

### ISSUE THREAD

**Issue by sidav** [jncraton/BWMetaAI#30]
I've played against Zerg (1v1) as Protoss and Terran, three times each. 
Each time Zerg did not attack me. It has 3-4 hatcheries, many zerglings, but that's all. It doesn't attack (although it actively protects its bases), and it doesn't react to my air units (it only builds spore colonies). 
I tried waiting, but the AI doesn't improve its tech and still does not attack. 
I play the latest battle.net version of Remastered and the latest release of AI. 
Terran and Protoss AIs are ok, and I've not tried ZvZ yet. I also seen Zerg attacking and improving tech in 8-player FFA game. 
Can I somehow help with diagnosing the issue?

**Comment by BoneHorror** [comment]
Unmodded remastered currently terribly mishandles AI priority (and probably always will since the game isn't quite actively patched anymore), but you can experiment with adding aise to BWMetaAI and seeing if it works https://github.com/neivv/aise/

**Comment by shashibici** [comment]
> 
> 
> Unmodded remastered currently terribly mishandles AI priority (and probably always will since the game isn't quite actively patched anymore), but you can experiment with adding aise to BWMetaAI and seeing if it works https://github.com/neivv/aise/ (using samase of course)

Is there a document telling about how to compile/build/install the `aise`  with samase? 
I am really seeking some enhanced AI's.
