### ISSUE TITLE
EUD MAPS (last release triggers)

### ISSUE THREAD

**Issue by eudmaptester** [jncraton/BWMetaAI#34]
Hi. thanks for work first of all. I compare triggers from EUD maps 2.3-alpha with 2.3 and 2.4. 
They have same number of lines : 37885.

 Does it mean that changes you have already done in 2.4 (Added 1 Gate Zealot Dragoon Pressure in PvT) and 2.3(bug fix) are not applied in EUD maps triggers and only can be found in aiscript.bin and tried with samase?

**Comment by jncraton** [comment]
Everything should be included in the EUD maps. I have aiscript.bin padded to a fixed length, and the triggers always write the whole file, so the length of the triggers won't typically change between versions.
