### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by BingleBingle** [jncraton/BWMetaAI#35]
I don't know if I can write this article here.
But something suspicious has gone wrong.
This error occurred while running BWMAI on samase-0.7.31.exe.
The BWMAI version I use is 2.4. 
Below is the full text of the error. 

─────────────────────────────────────────────────┐
samase
─────────────────────────────────────────────────┤
This mod has crashed.

Crash dump has been stored to
'C:\Users\cctv0(username)\AppData\Local\Temp\samase\2021-09-06-16-34-44'

Note:
Game build is 9713
Loader version is 0.7.31
─────────────────────────────────────────────────┘

(For reference, the BWMAI execution method was followed.)
So far, I have never had an error while approaching dozens of editions, but suddenly an error occurred today.
I turned on BlueStacks 5 while running BWMAI, but I don't know if this is directly related.
Do you know the cause of the error?
If you know, can you tell me?

**Comment by jncraton** [comment]
Thanks for reporting this. I'm not sure what has caused this error. It is very uncommon in my experience for BWMetaAI to completely crash the game.
