### ISSUE TITLE
how to add orther build?

### ISSUE THREAD

**Issue by llIllIllllIIIlllllll** [jncraton/BWMetaAI#36]
I want to add a lot of strategies

https://namu.wiki/w/%EB%B6%84%EB%A5%98:%EC%8A%A4%ED%83%80%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8/%EC%A0%84%EB%9E%B5%EC%A0%84%EC%88%A0?namespace=%EB%AC%B8%EC%84%9C

**Comment by jncraton** [comment]
Once you have things [building from source](https://github.com/jncraton/BWMetaAI/blob/master/CONTRIBUTING.md) it's pretty straightforward. One simple example currently is [Z Core Z expand](https://github.com/jncraton/BWMetaAI/blob/e963c6648f3a89cff95325ad556bf9818c5e9519/src/protoss/builds/zcorez%20expand.pyai). If you are familiar with PyAI, all of that syntax is available to you with a few (custom extensions)[https://github.com/jncraton/BWMetaAI/blob/e963c6648f3a89cff95325ad556bf9818c5e9519/CONTRIBUTING.md#new-ai-commandsmacros]. All you should need to do is add a build order to the correct directory and the build system should pick it up and add it to the possible build orders.
