### ISSUE TITLE
Zerg does not make several upgrades

### ISSUE THREAD

**Issue by duran55** [jncraton/BWMetaAI#41]
Zerg does not make several tech/upgrades. For example the following are not made:
- overlord: speed, capacity, vision
- hydra: speed, range
- burrowing
- air units: attack and armor

I checked tech_manager.pyai for Zerg and indeed they are missing. Do you want PR?

**Comment by jncraton** [comment]
Thanks for this. I'm open to this change if you can find a good pacing that doesn't stall things out in the late game too much.

I would prefer for burrow to not be researched, as it doesn't add much value and makes the bot feel a bit odd. I also do not see a reason for Overlord vision, as I do not think that there is much benefit to this for a bot.

I think it is best to not focus much on air upgrades until ground upgrades are complete. The other races skip air upgrades entirely, but Zerg does use air more, so these are probably a good idea here.

The other upgrades listed are reasonable, and I'd be happy to see them integrated.
