### ISSUE TITLE
Where is 'build_start' defined?

### ISSUE THREAD

**Issue by ajujoa** [jncraton/BWMetaAI#43]
I am checking and testing 'build' related commands.
but still immature.
Where is 'build_start'?
Because 'build_start' is used in many pyai. I really want to find it.
An additional question is, where is the short command? 
(Protoss Probe -> Probe, Protoss Cybernetics Core -> Core)
Anyone who knows please let me know.

**Comment by BoneHorror** [comment]
build_start is defined as a macro in tools/macros.js, it's not an ASC3 command by itself.
Abbreviations are in tools/abbrevs.json here or in unitdef.txt in PyAI

**Comment by jncraton** [comment]
@BoneHorror Thanks for sharing that information.

Some of this is also covered at a higher level in [CONTRIBUTING.md](CONTRIBUTING.md).
