### ISSUE TITLE
The default source does not use 'tech_manager'.

### ISSUE THREAD

**Issue by ajujoa** [jncraton/BWMetaAI#44]
Hi.
I'm trying out several test and build changes.
However, I encountered an unknown error in some parts.

1) AI ​​doesn't upgrade. The default source does not use 'tech_manager'. 
2) build -> 'upgrade(1, Protoss Ground Weapons, 30)' not working.
3) I cannot make more than 30 'probe'. It also stops at the build order.
4) AI cannot use more than 3 gases. It seems to recognize only three.

If you know anything about this, please reply.
Thanks.

**Comment by jncraton** [comment]
If you are modifying/adding builds to this project, the tech_manager will not be called until after your build finishes. This gives you control over which upgrades, if any, to include in your build.

Upgrades should work fine within a build. The [`+1 5 Rax`](https://github.com/jncraton/BWMetaAI/blob/daed5749efacebe16d7d50f70857d2c39fb98178/src/terran/builds/%2B1%205%20Rax.pyai) build includes upgrades if any example is helpful.

**Comment by ajujoa** [comment]
I found it in '+1 5 Rax.pyai'.
What is the difference 'upgrade' and 'tech'?
