### ISSUE TITLE
No comsat and turrets agianst protoss

### ISSUE THREAD

**Issue by duran55** [jncraton/BWMetaAI#50]
In PvT I make Stargate only to build few arbiters very late in the game (after 30 mins). At this point of time all of the map is expanded by AI and me, so no new expands are available. The map is Luna (4 starting locations).
This leads to two issues for the Terran AI (in town manager):
- no single comsat build against the arbiters
- no turrets in main and expands to protect the base/mines from observers

I have one quick fix in mind: just put check for citadel of adun in addition to "if enemyownsairtech".
Other option is to wait fixed amount of game time passed (against Protoss) and then build comsat and turrets.

**Comment by duran55** [comment]
PR created: #51

**Comment by jncraton** [comment]
I wouldn't expect your PR to fix this specific issue (no Comsat vs Arbiters), as these should have been built [once you completed your Stargate](https://github.com/jncraton/BWMetaAI/blob/dee972246fb67cf25cfcb67b8f388ae864b5b82e/tools/macros.js#L170). I suspect there is a deeper issue here. There are many things that could cause the script to lock in a long game (e.g. killing an SCV while it is building a building).

**Comment by duran55** [comment]
Maybe I was not clear enough in the first post. The issue is that I make Stargate (not only arbiters) very late in the game. At that time all of the town managers are completed and not executed anymore (correct me if I am wrong). So the check "if enemyownsairtech" is always false. No issue with that logic. That's why I added additional check against Protoss. The fix is tested and working as expected.

**Comment by jncraton** [comment]
If I'm reading your fix correctly, it adds a check for a Citadel to the same loop that is already checking for a Stargate. If you build a Stargate at any point in the game, this should already trigger to build Comsats and Turrets. Adding an additional check for a Citadel would make this trigger earlier in certain cases, but I don't think that is desirable.
