### ISSUE TITLE
Discord for the project

### ISSUE THREAD

**Issue by Ezro** [jncraton/BWMetaAI#58]
Hey, I just started getting into this project yesterday and was wondering if there was any desire to have a discord server for the project.

I think it could be a cool place to have discussion and collaboration (especially for something like https://github.com/jncraton/BWMetaAI/issues/57)

**Comment by jncraton** [comment]
If that's helpful for the community, feel free to create one. I personally don't interact with Discord much, so I'm not likely to keep up with discussion there.
