### ISSUE TITLE
[Question] Replays wrong. How to fix it?

### ISSUE THREAD

**Issue by robotimmy** [jncraton/BWMetaAI#59]
When watching a replay against BWMmetaAI bot, the replay is totally different from played game. E.g. I won the game, but in replay I lost. Also porbes do not build anything after some minutes. What can I do to make the replay work?

samase 0.8.31
aiscript.bin 2.5
SC:R 1.23.10.12409

**Comment by jncraton** [comment]
Is this an older replay or a game that you just played? Replays should work, but you'll need to using the same version of BWMetaAI and SC that you were using when you played the game. If it is an older replay, you can find old version of the bot in the [releases](https://github.com/jncraton/BWMetaAI/releases).

**Comment by BoneHorror** [comment]
In samase this will just happen, there are lots of issues that break replays

**Comment by jncraton** [comment]
@BoneHorror Thanks for sharing. That's helpful to know.

**Comment by robotimmy** [comment]
It's a game I just played with Starcraft Remastered and samase launcher. Looks like samase brakes replays not BWMetaAI?
